name: PyInstaller

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./standalone
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip
        pip install pyinstaller==4.7
        cp -force dep/bootloader/* $pythonLocation/Lib/site-packages/PyInstaller/bootloader/Windows-64bit/
    - name: build with pyinstaller
      run: |
        pyinstaller TissUUmaps.spec
    - name: copy vips bin files
      run: |
        cp dep/vips-dev-8.10/bin/* dist/TissUUmaps/
        
    - name: Checkout fred
      uses: actions/checkout@v2
      with:
        repository: 'freenet/fred'
        fetch-depth: 0
        path: 'fred'

    - name: Download fred from the Github Release
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: "freenet"
        repo: "fred"
        tag: "latest"
        file: "freenet.jar"

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "build_installer.iss"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      with:
        path: "standalone/dist/TissUUmaps_winInstaller.exe"
        name: TissUUmaps_winInstaller.exe
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: TissUUmaps_winInstaller.exe
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
          TissUUmaps_winInstaller.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
